### ISSUE TITLE
[Suggestion] Display the heading more fully

### ISSUE THREAD

**Issue by trmdi** [Zren/plasma-applet-githubissues#4]
For example, display the repo name in a new line, or use a smaller fontsize...
Anyhow, I think it need to be more responsive.

![image](https://user-images.githubusercontent.com/11857205/48399197-930ae000-e755-11e8-9528-b191c1c83e0a.png)

Finally, I just want to say: your applet looks very nice !

**Comment by Zren** [comment]
Yeah, long names don't mesh well with the thin width. I could use `fontSizeMode: Text.Fit` instead of an ellipsis. the heading size would differ between side by side widgets though.

Hmm, looks like I'm not scaling by dpi, oops.

It's currently `24px`, which I chose randomly it seems.

* The repo name is `18px` on this page.
* The issue titles are `16px` in the issue list page.

Here's what it looks like with `18px` on the left, and demonstrates that it'll still cutoff really long entries when it hits... the minimum font size? In any case, the master branch currently shows a tooltip on hover when text text is truncated.

![2018-11-13___22-05-02](https://user-images.githubusercontent.com/416367/48457454-cc147600-e790-11e8-807c-fac0aeff82d4.png)

I plan on making the heading configurable eventually. I'm considering having a single widget list issues from multiple repos [like my bugzilla widget](https://github.com/Zren/plasma-applet-bugzilla#bugzilla-widget), so we'll need to have the ability to customize the heading.

**Comment by Zren** [comment]
The 18px font size change is in the v3 release.
